# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty


# Social Networks
twitter_username: MrNox_
github_username:  MrNox
youtube_channel:  UCg01TfhxLro71ppULtIBAjw

# Setup
title:            Whoami
tagline:          "A Jekyll theme"
description:      "Nox's projects, conferences, blogposts and more..."
url:              https://nox.reversingcode.re
baseurl:          /

author:
  name:           'Nox'
  url:            https://twitter.com/mrnox_

paginate:         5

# Custom vars
version:          2.1.0

plugins:
  - jekyll-paginate
  - jekyll-gist

github:
  repo:           https://github.com/MrNox
