# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty


# Social Networks
twitter_username: MrNox_
github_username:  MrNox
youtube_channel:  UCg01TfhxLro71ppULtIBAjw
email:            nox@reversingcode.re

# Setup
title:            "Nox's website"
tagline:          "Pwner"
description:      "Nox's projects, talks, blogposts and more..."
url:              https://noxhax.me
baseurl:          /

author:
  title:          "Josué R."
  name:           'Nox'
  url:            https://twitter.com/mrnox_

paginate:         5

# Custom vars
version:          2.1.0

plugins:
  - jekyll-paginate
  - jekyll-gist

github:
  repo:           https://github.com/MrNox
